<project name="FAE Scheme" default="main">
    <property environment="env"/>

    <target name="clean">
        <delete dir="bin"/>
    </target>

    <path id="bin.classpath">
        <pathelement location="bin"/>
    </path>

    <target name="parser">
        <mkdir dir="src/parser"/>
        <javacc target="grammar/Parser.jj"
            javacchome="${env.JAVACC_HOME}"
            outputdirectory="src/parser"/>
    </target>

    <target name="compile" depends="parser">
        <mkdir dir="bin"/>

        <javac srcdir="src" destdir="bin"
            debug="true"
            includeantruntime="false"/>
    </target>

    <target name="main" depends="compile" />

    <target name="run" depends="main">
        <java classname="interp.REPL" classpath="bin">
        </java>
    </target>

</project>
