PARSER_BEGIN(Parser)
package parser;

import ast.*;

public class Parser {}

PARSER_END(Parser)

SKIP:
{
    " "
  | "\t"
  | "\n"
  | "\r"
  | <"%" (~["\n","\r"])* ("\n"|"\r")>
}

TOKEN:
{
      <LPAR    : "(">
    | <RPAR    : ")">
    | <INTEGER : ("-")? (["0"-"9"])+>
    | <LAMBDA  : "lambda">
    | <LET     : "let">
    | <ADD     : "+">
    | <SYMBOL  : (["a"-"z", "A"-"Z"])*>
}

TOKEN:
{
    <ERROR : ~[]>
}

ASTNode atom():
{
    Token token;
    ASTNode node;
}
{
    (
      token = <INTEGER> { node = new IntegerNode(token.image); }
    | token = <SYMBOL>  { node = new SymbolNode(token.image); }
    )
    {
        return node;
    }
}

ASTNode list():
{
    ASTNode  node = null, t;
}
{
  (
    <LPAR>
    (
        node = list()
        | node = add()
        | node = let()    
        | node = lambda() 
        | node = atom()   
    )
    <RPAR>
    { return node; }
  )
  |
  <EOF> { return null; }
}

ASTNode add():
{
    ASTNode node,
            lhs,
            rhs;
}
{
    <ADD>
    (
    (
      lhs = list()
    | lhs = atom()
    )
    (
      rhs = list()
    | rhs = atom()
    )
    )
    {
        return new AdditionNode(lhs, rhs);
    }
}

ASTNode let():
{
    ASTNode node,
            bindings,
            body;
}
{
    <LET>
    bindings = list()
    body     = list()
    {
        return new LetNode(bindings, body);
    }
}

ASTNode lambda():
{
    ASTNode node,
            params,
            body;
}
{
    <LAMBDA>
    params  = list()
    body    = list()
    {
        return new LambdaNode(params, body);
    }
}
